# https://aka.ms/yaml

trigger:
- master
- develop

jobs:

- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - script: |
        sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev
        display-name: 'Install dependencies'
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'

- job: MacOS
  pool:
    vmImage: macos-10.15
  steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'
