# https://aka.ms/yaml

trigger:
- master
- develop

jobs:

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        sudo apt-get install -y zlib1g-dev libbz2-dev liblzma-dev
        display-name: 'Install dependencies'
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'

- job: MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
    - task: CMake@1
      inputs:
        cmakeArgs: '-DENABLE_7Z=ON -DBUILD_SAMPLES=ON ..'
